version: '3'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
  node:
    restart: always
    build: .
    ports:
      - 80:3050
    volumes:
      - ./:/code
    depends_on: 
      - mongo
volumes:
  mongodb: